### ISSUE TITLE
Support Casbin as the authorization backend

### ISSUE THREAD

**Issue by hsluoyz** [nclandrei/SyncTube#1]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current ACL middleware. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by nclandrei** [comment]
Thanks a lot for your interest in contributing to YouTube Sync. In the context of this application, what do you think Casbin would bring to the table? I had a look at Casbin and it looks really promising, thus if there would be clear benefits to using it instead of ACL m/w, then I would be more than glad to help you with a new PR.

**Comment by hsluoyz** [comment]
Hi @nclandrei ,

The benefit is that the middleware in https://github.com/nclandrei/YTSync/blob/master/route/route.go#L66 will be simplified and replaced by Casbin policy rules. By using the regex and keyMatch methods in Casbin, the number of resulting policy rules can be much smaller than the original middleware in routes. So the developer can easily modify them in future.

A similar example for another project grafana is here: https://github.com/casbin/grafana/commit/696ed4e03ffa49b4261c16035a24e4980c17c2c1
